steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'get-key'
    entrypoint: 'bash'
    dir: .
    args:
    - '-c'
    - |
      gcloud secrets versions access latest --secret="github" --project="eventrun" > /root/.ssh/id_rsa
    volumes:
    - name: 'ssh'
      path: /root/.ssh
  - name: 'gcr.io/cloud-builders/git'
    id: 'add-key'
    entrypoint: 'bash'
    dir: .
    args:
    - '-c'
    - |
      chmod 600 /root/.ssh/id_rsa
      cat <<EOF >/root/.ssh/config
      Hostname github.com
      IdentityFile /root/.ssh/id_rsa
      EOF
      ssh-keyscan -t rsa github.com > /root/.ssh/known_hosts
    volumes:
    - name: 'ssh'
      path: /root/.ssh
  - name: 'gcr.io/cloud-builders/git'
    id: 'crlf'
    entrypoint: 'bash'
    args:
    - '-c'
    - |
      git config --global core.autocrlf input
      git reset --hard
      git clean -fdx
    volumes:
    - name: 'ssh'
      path: /root/.ssh


options:
  substitution_option: 'ALLOW_LOOSE'

substitutions:
  _KEY_VERISON: "latest"
  _KEY_PROJECT: "eventrun"
  _BASE_BRANCH: "main"
  _ENV: "np"
  _CUSTOM_TAG: ""
  _SNAPSHOT_ARTIFACTS_BUCKET: ""

timeout: 600s